sudo: required

language: go

os:
  - linux
#  - osx

#branches:
#  only:
#    - master
#    - develop

go:
  - "1.12"

env:
  - DING_TOKEN="5349ab8e8a4ec739e5f2c704ebdcf50bf1e52c5b925d176a871c4e5b98735a20"

services:
  - docker

go_import_path: github.com/logancloud/logan-app-operator

before_install:
  - wget https://github.com/operator-framework/operator-sdk/releases/download/v0.8.1/operator-sdk-v0.8.1-x86_64-linux-gnu
  - mkdir -p $HOME/bin
  - mv operator-sdk-v0.8.1-x86_64-linux-gnu $HOME/bin/operator-sdk
  - chmod +x $HOME/bin/operator-sdk
  - export PATH="$HOME/bin:$PATH"

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/onsi/ginkgo/ginkgo

script:
  - curl 'https://oapi.dingtalk.com/robot/send?access_token=5349ab8e8a4ec739e5f2c704ebdcf50bf1e52c5b925d176a871c4e5b98735a20' \
    -H 'Content-Type: application/json' \
    -d '{"msgtype": "text",
                      "text": {
                        "content": "test"
                      }
    }'
  - make docker-build
  - make travis-build

after_script:
  - docker logout

notifications:
  email: false
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=$DING_TOKEN