sudo: required
dist: xenial
language: go

os:
  - linux

go:
  - "1.12.x"

env:
  - TEST_SUITE=units
  - TEST_SUITE=integration
  - TEST_SUITE=1
  - TEST_SUITE=2

services:
  - docker

go_import_path: github.com/logancloud/logan-app-operator

cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin
    - $HOME/.cache/go-build

before_install:
  - export TRAVIS_SD_START_TIME=$(date -u +%s)
  - bash ./scripts/display-system-info.sh
install:
  - bash ./scripts/install.sh

script: bash test.sh $TEST_SUITE

after_script:
  - docker logout
  - make dingding

after_failure:
  - export TRAVIS_SD_STATUS=failed

after_success:
  - export TRAVIS_SD_STATUS=succeeded

notifications:
  email: false